"""
Django settings for cls project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import codecs
import os
from ConfigParser import SafeConfigParser
from os.path import dirname, normpath, join

CANVAS_URL = "https://canvas.ou.edu/api/v1/"
CANVAS_TOKEN = "8808~1HTPVyS2HJGvVKFyDCaPxGVzi1Kygy7TI0czE8E4F523EUWGcpKvOA7p9TJZnJIr"


ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window; you may, of course, use a different value.

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Absolute filesystem path to the top-level project folder:
SITE_ROOT = dirname(BASE_DIR)

STORAGE_DIR = normpath(join(SITE_ROOT, 'storage'))

# STATIC FILE CONFIGURATION
# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = normpath(join(STORAGE_DIR, 'static'))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATICFILES_DIRS = (normpath(join(BASE_DIR, 'assets')),)
STATIC_URL = '/static/'


# MEDIA CONFIGURATION
# See: https://docs.djangoproject.com/en/dev/ref/settings/#media-root
MEDIA_ROOT = normpath(join(STORAGE_DIR, 'media'))

MEDIA_URL = '/media/'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hu)d#zr+sun0nsi@=(4vg9_&nh08hefrhghekf*z9venx@1=v8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


FIXTURE_DIRS = (
    normpath(join(BASE_DIR, 'fixtures')),
)

#Debug Toolbar
INTERNAL_IPS=('127.0.0.1','129.15.66.222')

DEBUG_TOOLBAR_PATCH_SETTINGS = False


#def show_toolbar(request):
#    return True
#DEBUG_TOOLBAR_CONFIG = {
#    "SHOW_TOOLBAR_CALLBACK" : show_toolbar,
#}

# Application definition
DJANGO_APPS = (
    'toolkit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

THIRD_PARTY_APPS = (
    'cuser',  # CurrentUserField
    'widget_tweaks',  # django widget tweaks
    'django_behave',
    'splinter',
    'canvasapi',
)
CUSTOM_APPS = (
    'profiles',
    'resources',
    'ap',
)

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + CUSTOM_APPS


MIDDLEWARE_CLASSES = [
#    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cuser.middleware.CuserMiddleware',  # CurrentUserField
]

ROOT_URLCONF = 'nucleus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            normpath(join(BASE_DIR, 'templates')),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            #'builtins': ['toolkit.templatetags'],
        },
    },
]

WSGI_APPLICATION = 'nucleus.wsgi.application'

 
# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dev-pacs-portal',
        'USER': 'pacsportal-dev',
        'PASSWORD': 'w725D0DPu3',
        'HOST': 'monopolyjr.ce.ou.edu',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Chicago'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# E-mail settings
EMAIL_HOST = 'hermod.occe.ou.edu'
#EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'clsat@ou.edu'


LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'



