# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-05 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_by', models.CharField(default=None, max_length=8)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default=None, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
