# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-05 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursechangerequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='coursechangerequest',
            name='last_updated_by',
        ),
        migrations.DeleteModel(
            name='CourseChangeRequest',
        ),
    ]
